#!/usr/bin/env bash

# parse args
show_help=0
show_msg=0
show_install=0
force_reinstall=0
show_version=0
arg="$1"
while [ -n "$arg" ];do
    if [[ "$arg" == "-h" || $arg == "--help" ]];then
        show_help=1
        break
    elif [[ "$arg" == "-m" || "$arg" == "--show-msg" ]];then
        show_msg=1
    elif [[ "$arg" == "-i" || "$arg" == "--show-install" ]];then
        show_install=1
    elif [[ "$arg" == "-r" || "$arg" == "--reinstall" ]];then
        force_reinstall=1
    elif [[ "$arg" == "-v" || "$arg" == "--version" ]];then
        show_version=1
        break
    elif [[ "$arg" == "-"* ]];then
        if [[ "$arg" == "--"* ]];then
            echo "x Invalid arg '$arg', see -h or --help for info"
            exit 1
        fi
        while read -rn1 char;do
            if [ -z "$char" ];then
                break
            elif [[ "$char" == "h" ]];then
                show_help=1
                break 2
            elif [[ "$char" == "m" ]];then
                show_msg=1
            elif [[ "$char" == "i" ]];then
                show_install=1
            elif [[ "$char" == "r" ]];then
                force_reinstall=1
            elif [[ "$char" == "v" ]];then
                show_version=1
                break 2
            else
                echo "x Invalid short arg '$char', see -h or --help for info"
                exit 1
            fi
        done < <(echo "$arg" | cut -c2-)
    else
        break
    fi
    shift
    arg=$1
done
shift

# early exit paths
if [ "$show_version" == 1 ];then
    echo "This is tppr version 0.1.0"
    echo "The Tiny Portable Python Runner for hassle-free venv and dep handling"
    echo "Please see https://github.com/Jelmerro/tppr for updates and info"
    exit
fi
if [ "$show_help" == 1 ];then
    echo "Usage: ./tppr [options] file ..."
    echo
    echo "Tiny Portable Python Runner for hassle-free venv and dep handling"
    echo
    echo "positional args:"
    echo "  file  Python script file to run within a project venv"
    echo "  ...   Any arguments meant for the python script go here"
    echo
    echo "options:"
    echo "  -h, --help          Show this help message and exit"
    echo "  -m, --show-msg      Print tppr info messages while preparing to run"
    echo "  -i, --show-install  Print pip requirements installation output"
    echo "  -r, --reinstall     Reinstall regardless of a correctly versioned venv"
    echo "  -v, --version       Show program version info and exit"
    exit
fi
if [ -z "$arg" ] || [ "$arg" == "" ];then
    echo "x No file argument found, see -h or --help for info"
    exit 1
fi
file=$(realpath "$arg")
if [ ! -f "$file" ];then
    echo "x File $file not found"
    exit 1
fi

# echo helper to only show messages if enabled
msg() {
    if [ "$show_msg" == 1 ];then
        echo "$1"
    fi
}

# project base dir, or run with plain python binary if not found
dir=$(dirname "$file")
while [[ ! -f "$dir/requirements.txt" && ! -f "$dir/pyproject.toml" && "$dir" != "/" ]];do
    dir=$(dirname "$dir")
done
if [[ "$dir" == "/" ]];then
    msg "> project dir not found, running with system python"
    python "$file" "$@"
    exit
fi
msg "> project dir detected as $dir"

# find latest python version and latest executable paths
full_version=$(python -c "import platform;print(platform.python_version())")
version=${full_version%.*}
python="$dir/venv/bin/python$version"
pip="$dir/venv/bin/pip$version"
activate="$dir/venv/bin/activate"

# delete existing venv if outdated, incomplete or forced to be deleted
if [ -d "$dir/venv" ];then
    if [ ! -f "$python" ]  || [ ! -f "$pip" ] || [ ! -f "$activate" ];then
        msg "> deleting existing venv"
        rm -rf "$dir/venv"
    elif [ "$force_reinstall" == 1 ];then
        msg "> force deleting existing valid venv"
        rm -rf "$dir/venv"
    fi
fi

# create new venv and install deps, then source it
if [ ! -f "$python" ] || [ ! -f "$pip" ] || [ ! -f "$activate" ];then
    msg "> creating venv"
    "python$version" -m venv "$dir/venv"
    source "$activate"
    stdout="/dev/stdout"
    stderr="/dev/stderr"
    if [ "$show_install" == 0 ];then
        stdout="/dev/null"
        stderr="/dev/null"
    fi
    if [ -f "$dir/requirements.txt" ];then
       "$pip" install -r "$dir/requirements.txt" 2>$stderr >$stdout
    fi
    "$pip" install "$dir" 2>$stderr >$stdout
    msg "> sourced, installed and done"
else
    source "$activate"
fi

# run the file with venv's python
msg "$ $python"
"$python" "$file" "$@"
